const scenes=[...document.querySelectorAll('.scene')];let current=0;const transition=document.getElementById('transition');
const music=document.getElementById('music'),musicPill=document.getElementById('musicPill'),musicToggle=document.getElementById('musicToggle');
function showScene(index){if(index<0||index>=scenes.length||index===current)return;transition.classList.remove('go');void transition.offsetWidth;transition.classList.add('go');setTimeout(()=>{scenes[current].classList.remove('active');current=index;scenes[current].classList.add('active');onScene(index)},480)}
function onScene(index){const name=scenes[index].dataset.scene;if(name==='memories'&&music.paused){music.currentTime=93;music.play().catch(()=>{});musicPill.classList.add('visible');musicToggle.textContent='Ⅱ'}if(name==='letterPage')typeText('letterText',`Merci pour tous nos moments, nos sourires et tous les souvenirs que nous avons déjà créés.\n\nCette version sert surtout à te montrer le rendu visuel. Le vrai texte sera remplacé ensuite, mot par mot, exactement comme tu le souhaites.\n\n— Abdulkaan`,34);if(name==='dua')typeText('duaText',`Ya Allah, protège Lydia Kara, accorde-lui la paix, la santé, le bonheur et la réussite.\n\nGuide chacun de ses pas vers ce qui est bon et préserve son cœur de toute tristesse.\n\nAmeen.`,30)}
document.querySelectorAll('.next').forEach(b=>b.addEventListener('click',()=>showScene(current+1)));document.getElementById('restart').addEventListener('click',()=>showScene(1));
const keypad=document.getElementById('keypad');let code='';[1,2,3,4,5,6,7,8,9,'',0,'⌫'].forEach(v=>{if(v===''){keypad.append(document.createElement('span'));return}const b=document.createElement('button');b.textContent=v;b.onclick=()=>v==='⌫'?erase():add(String(v));keypad.append(b)});function paint(){document.querySelectorAll('#pin i').forEach((d,i)=>d.classList.toggle('filled',i<code.length))}function erase(){code=code.slice(0,-1);paint()}function add(n){if(code.length<4)code+=n;paint();if(code.length===4)setTimeout(()=>{if(code==='1009'){document.getElementById('error').textContent='';showScene(1)}else{document.getElementById('error').textContent='Ce n’est pas le bon code';navigator.vibrate?.([50,40,50]);code='';paint()}},180)}document.getElementById('erase').onclick=erase;
document.querySelectorAll('.quiz-card').forEach(c=>c.onclick=()=>c.classList.toggle('revealed'));document.getElementById('envelope').onclick=()=>showScene(current+1);
function typeText(id,text,speed){const el=document.getElementById(id);el.textContent='';let i=0;clearInterval(el.timer);el.timer=setInterval(()=>{el.textContent+=text[i++]||'';if(i>=text.length)clearInterval(el.timer)},speed)}
musicToggle.onclick=()=>{if(music.paused){music.play();musicToggle.textContent='Ⅱ'}else{music.pause();musicToggle.textContent='♪'}};
const stage=document.getElementById('memoryStage'),startBtn=document.getElementById('startMemories');const photos=Array.from({length:15},(_,i)=>`assets/photos/photo-${String(i+1).padStart(2,'0')}.jpg`);let memoryRunning=false;
startBtn.onclick=async()=>{if(memoryRunning)return;memoryRunning=true;startBtn.style.display='none';stage.innerHTML='';for(let i=0;i<photos.length;i++){const img=document.createElement('img');img.src=photos[i];img.className='memory-photo';img.style.setProperty('--r',`${(Math.random()*10-5).toFixed(1)}deg`);stage.append(img);await wait(80);img.classList.add('show');await wait(1180);if(i<photos.length-1){img.classList.remove('show');await wait(420)}}const imgs=[...stage.querySelectorAll('img')];imgs.forEach((img,i)=>{img.className='memory-photo collage';img.style.setProperty('--x',`${13+(i%5)*18.5}%`);img.style.setProperty('--y',`${19+Math.floor(i/5)*31}%`);img.style.setProperty('--r',`${[-7,5,-3,7,-5][i%5]}deg`)})};function wait(ms){return new Promise(r=>setTimeout(r,ms))}
let touchX=0;document.addEventListener('touchstart',e=>touchX=e.touches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-touchX;if(Math.abs(d)>100&&current>0&&!memoryRunning)showScene(current+(d<0?1:-1))},{passive:true});
